{{- if .Values.security.networkPolicy.enabled -}}
{{- if .Values.ingress.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "yatai.fullname" . }}-2
spec:
  podSelector:
    matchLabels:
      {{- include "yatai.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    {{- toYaml .Values.security.networkPolicy.from | indent 4 }}
  policyTypes:
  - Ingress
{{- end }}
{{- end }}
