apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yatai-deployment.shared-envname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yatai-deployment.labels" . | nindent 4 }}
type: Opaque
stringData:
  YATAI_DEPLOYMENT_NAMESPACE: {{ .Release.Namespace }}
  BENTO_DEPLOYMENT_NAMESPACES: {{ .Release.Namespace }}
