apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "yatai-image-builder.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yatai-image-builder.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "yatai-image-builder.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
  - {{ include "yatai-image-builder.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "yatai-image-builder.fullname" . }}-selfsigned-issuer
  secretName: {{ include "yatai-image-builder.fullname" . }}-webhook-server-cert
