apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "yatai-image-builder.serviceAccountName" . }}-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "yatai-image-builder.serviceAccountName" . }}-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "yatai-image-builder.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
