apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yatai-image-builder.shared-envname" . }}
  labels:
    {{- include "yatai-image-builder.labels" . | nindent 4 }}
type: Opaque
stringData:
  YATAI_IMAGE_BUILDER_NAMESPACE: {{ .Release.Namespace }}
