apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yatai.envname" . }}
  labels:
  {{- include "yatai.labels" . | nindent 4 }}
type: Opaque
stringData:
  YATAI_INITIALIZATION_TOKEN: {{ include "yatai.initializationToken" . | quote }}
  SESSION_SECRET_KEY: {{ include "yatai.sessionSecretKey" . | quote }}
  YATAI_DEPLOYMENT_NAMESPACE: "{{ .Release.Namespace }}"
  YATAI_SYSTEM_NAMESPACE: "{{ .Release.Namespace }}"

  PG_HOST: {{ .Values.postgresql.fullnameOverride }}
  PG_DATABASE: {{ .Values.global.postgresql.auth.database | quote }}
  PG_PORT: "5432"
  PG_SSLMODE: "disable"
  PG_USER: "postgres"
  PG_PASSWORD: {{ .Values.global.postgresql.auth.postgresPassword | quote }}
  S3_ENDPOINT: {{ .Values.s3.endpoint | quote }}
  S3_REGION: {{ .Values.s3.region | quote }}
  S3_BUCKET_NAME: {{ .Values.s3.bucketName | quote }}
  S3_SECURE: {{ .Values.s3.secure | quote }}
  {{- if not .Values.s3.accessKeyExistingSecretName }}
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | quote }}
  {{- end }}
  {{- if not .Values.s3.secretKeyExistingSecretName }}
  S3_SECRET_KEY: {{ .Values.s3.secretKey | quote }}
  {{- end }}
  USERNAME: {{ .Values.security.username }}
  EMAIL: {{ .Values.security.email }}
  PASSWORD: {{ .Values.security.password }}

  TRANSMISSION_STRATEGY: {{ .Values.transmissionStrategy | quote }}
