apiVersion: v1
kind: Secret
metadata:
  name: yatai-common-env
  labels:
  {{- include "yatai.labels" . | nindent 4 }}
type: Opaque
stringData:
  YATAI_ENDPOINT: "http://{{ .Values.ingress.host }}"
  YATAI_CLUSTER_NAME: "default"
  YATAI_DEPLOYMENT_NAMESPACE: "{{ .Release.Namespace }}"
  YATAI_API_TOKEN: "{{ .Values.security.password }}"
