apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metaflow-ui.fullname" . }}
  labels:
    {{- include "metaflow-ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "metaflow-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metaflow-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "metaflow-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-postgresql
          image: "alpine"
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              until printf "." && nc -z -w 2 {{ .Values.postgresql.fullnameOverride }} 5432; do
                  sleep 2;
              done;
              echo 'PostgreSQL OK ✓' 
      containers:
        - name: {{ include "metaflow-ui.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.service.image.repository }}:{{ .Values.service.image.tag | default .Chart.AppVersion }}"
          command: ["/opt/latest/bin/python3", "-m", "services.ui_backend_service.ui_server" ]
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP

          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- range .Values.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            - name: UI_ENABLED
              value: "1"
            - name: PATH_PREFIX
              value: "/api"
            - name: MF_DATASTORE_ROOT
              value: {{ .Values.service.METAFLOW_DATASTORE_SYSROOT_S3 | quote }}
            - name: METAFLOW_DATASTORE_SYSROOT_S3
              value: {{ .Values.service.METAFLOW_DATASTORE_SYSROOT_S3 | quote }}
            - name: LOGLEVEL
              value: "DEBUG"
            - name: METAFLOW_SERVICE_URL
              value: "http://localhost:8083/api/metadata"
            - name: METAFLOW_DEFAULT_DATASTORE
              value: "s3"
            - name: METAFLOW_DEFAULT_METADATA
              value: "service"
            {{- include "metaflow-ui.metadatadbEnvVars" . | nindent 12 }}
            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ .Values.s3.secretAccessKey }}"
            - name: AWS_ACCESS_KEY_IDD
              value: "{{ .Values.s3.accessKeyId }}"
            - name: AWS_S3_ENDPOINT
              value: "{{ .Values.s3.endpoint }}"
            - name: AWS_S3_DEFAULT_REGION
              value: "{{ .Values.s3.defaultRegion}}"
            - name: AWS_SESSION_TOKEN 
              value: "{{ .Values.s3.sessionToken }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
