{{- $fullname := (include "metaflow.fullname" .) -}}
{{- $secretName := printf "%s-%s" $fullname "s3" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey }}
  AWS_S3_ENDPOINT: {{ .Values.s3.endpoint }}
  AWS_DEFAULT_REGION: {{ .Values.s3.defaultRegion }}
  AWS_SESSION_TOKEN: {{ .Values.s3.sessionToken }}
