apiVersion: v1
kind: Secret
metadata:
  name: {{ include "library-chart.fullname" . }}
type: Opaque
data:
  username: {{ .Values.argilla.auth.username | b64enc | quote }}
  password: {{ .Values.argilla.auth.password | b64enc | quote }}
  apikey: {{ .Values.argilla.auth.apikey | b64enc | quote }}
  secretkey: {{ .Values.argilla.auth.secretkey | b64enc | quote }}
