apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    {{- include "library-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
  - name: http
    port: 6900
