{{- if .Values.discoverable.allow }}
{{- $fullname := (include "library-chart.fullname" .) -}}
{{- $secretName := printf "%s-%s" "discoverable" $fullname -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    onyxia/discovery: "mlflow"
type: Opaque
data:
  {{ if .Values.ingress.enabled }}
  uri: {{ printf "https://%s" .Values.ingress.hostname | b64enc | quote }}
  {{ else }}
  uri: {{ printf "http://%s" $fullname | b64enc | quote }}
  {{ end }}
{{- end -}}