{{- if .Values.security.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-mlflow-auth
stringData:
  basic_auth.ini: |
    [mlflow]
    default_permission = {{ .Values.security.defaultPermission }}
    database_uri = sqlite:///basic_auth.db
    admin_username = {{ .Values.security.username }}
    admin_password = {{ .Values.security.password }}
    authorization_function = mlflow.server.auth:authenticate_request_basic_auth
{{- end -}}