apiVersion: v2
name: label-studio
description: Data Science starts with data. Label Studio removes the pain of labeling it.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/labelStudio.png
keywords:
  - ML
home: https://labelstud.io/
sources:
  - https://github.com/InseeFrLab/helm-charts-automation/tree/master/charts/label-studio
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 3.0.9

dependencies:
  - name: library-chart
    version: 1.5.45
    repository: https://inseefrlab.github.io/helm-charts-interactive-services
