{{- with ((.Values.langfuse.langfuse.encryptionKey).secretKeyRef).name -}}

{{- $hexkey := "" }}
{{- range $i := until 64 }}
    {{- $rand_hex_char := mod (randNumeric 4 | atoi) 16 | printf "%x" }}
    {{- $hexkey = print $hexkey $rand_hex_char }}
{{- end }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ . }}
stringData:
  encryption-key: {{ $hexkey }}
{{- end -}}
