apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-cluster
  labels:
    argocd.argoproj.io/secret-type: cluster   
data:
  config: eyJ0bHNDbGllbnRDb25maWciOnsiaW5zZWN1cmUiOmZhbHNlfX0=
  name: aW5jbHVzdGVyCg==
  namespaces: {{ .Release.Namespace | b64enc }} 
  server: {{ .Values.apiserver | b64enc }} 
